package com.pipisou.pipisou.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
@ApiModel("搜索内容实体")
public class LinkInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkinfo.id
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    @ApiModelProperty("分享文件id")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkinfo.link_url
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    @ApiModelProperty("分享文件Url")
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkinfo.link_name
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    @ApiModelProperty("分享文件名称")
    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkinfo.link_passwd
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    @ApiModelProperty("分享文件密码")
    private String linkPasswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkinfo.link_data
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    @ApiModelProperty("分享文件时间")
    private String linkData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkinfo.size
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    @ApiModelProperty("分享文件大小")
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table linkinfo
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkinfo.id
     *
     * @return the value of linkinfo.id
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkinfo
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public LinkInfo withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkinfo.id
     *
     * @param id the value for linkinfo.id
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkinfo.link_url
     *
     * @return the value of linkinfo.link_url
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkinfo
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public LinkInfo withLinkUrl(String linkUrl) {
        this.setLinkUrl(linkUrl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkinfo.link_url
     *
     * @param linkUrl the value for linkinfo.link_url
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkinfo.link_name
     *
     * @return the value of linkinfo.link_name
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkinfo
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public LinkInfo withLinkName(String linkName) {
        this.setLinkName(linkName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkinfo.link_name
     *
     * @param linkName the value for linkinfo.link_name
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName == null ? null : linkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkinfo.link_passwd
     *
     * @return the value of linkinfo.link_passwd
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public String getLinkPasswd() {
        return linkPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkinfo
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public LinkInfo withLinkPasswd(String linkPasswd) {
        this.setLinkPasswd(linkPasswd);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkinfo.link_passwd
     *
     * @param linkPasswd the value for linkinfo.link_passwd
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public void setLinkPasswd(String linkPasswd) {
        this.linkPasswd = linkPasswd == null ? null : linkPasswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkinfo.link_data
     *
     * @return the value of linkinfo.link_data
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public String getLinkData() {
        return linkData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkinfo
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public LinkInfo withLinkData(String linkData) {
        this.setLinkData(linkData);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkinfo.link_data
     *
     * @param linkData the value for linkinfo.link_data
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public void setLinkData(String linkData) {
        this.linkData = linkData == null ? null : linkData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkinfo.size
     *
     * @return the value of linkinfo.size
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkinfo
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public LinkInfo withSize(String size) {
        this.setSize(size);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkinfo.size
     *
     * @param size the value for linkinfo.size
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkinfo
     *
     * @mbg.generated Thu Oct 03 21:33:11 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", linkUrl=").append(linkUrl);
        sb.append(", linkName=").append(linkName);
        sb.append(", linkPasswd=").append(linkPasswd);
        sb.append(", linkData=").append(linkData);
        sb.append(", size=").append(size);
        sb.append("]");
        return sb.toString();
    }
}